Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: news_articulo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 26, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
                                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: news_articulo
"GET / HTTP/1.1" 500 182286
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17309
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84151
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
Internal Server Error: /buscar/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/busqueda.html, news/articulo_list.html
"GET /buscar/?q= HTTP/1.1" 500 84449
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84151
Internal Server Error: /buscar/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/busqueda.html, news/articulo_list.html
"GET /buscar/?q= HTTP/1.1" 500 84449
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84151
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84151
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84151
"GET / HTTP/1.1" 200 17309
Internal Server Error: /estadisticas/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 195, in estadisticas_view
    return render(request, 'news/estadisticas.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/estadisticas.html
"GET /estadisticas/ HTTP/1.1" 500 83030
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
Not Found: /favicon.ico
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17309
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17309
Not Found: /favicon.ico
Internal Server Error: /estadisticas/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 195, in estadisticas_view
    return render(request, 'news/estadisticas.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/estadisticas.html
"GET /estadisticas/ HTTP/1.1" 500 83631
"GET / HTTP/1.1" 200 17309
"GET / HTTP/1.1" 200 17309
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4231
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/base.css HTTP/1.1" 200 22120
"GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 9041
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 9041
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17540
Internal Server Error: /estadisticas/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 195, in estadisticas_view
    return render(request, 'news/estadisticas.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/estadisticas.html
"GET /estadisticas/ HTTP/1.1" 500 83774
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84895
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84895
Internal Server Error: /autores/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autores_list.html, news/autor_list.html
"GET /autores/ HTTP/1.1" 500 84895
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /autores/ HTTP/1.1" 200 11437
"GET /autores/ HTTP/1.1" 200 11437
"GET /autores/ HTTP/1.1" 200 11437
"GET / HTTP/1.1" 200 17540
"GET /autores/ HTTP/1.1" 200 11437
Internal Server Error: /buscar/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/busqueda.html, news/articulo_list.html
"GET /buscar/?q= HTTP/1.1" 500 85201
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /autores/ HTTP/1.1" 200 11437
"GET / HTTP/1.1" 200 17540
"GET /buscar/?q= HTTP/1.1" 200 11489
"GET /buscar/?q=hgh HTTP/1.1" 200 11492
Internal Server Error: /estadisticas/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 195, in estadisticas_view
    return render(request, 'news/estadisticas.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/estadisticas.html
"GET /estadisticas/ HTTP/1.1" 500 84672
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /estadisticas/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/news/views.py", line 226, in estadisticas_view
    total_visitas = Articulo.objects.aggregate(total=models.Sum('vistas'))['total'] or 0
                                                     ^^^^^^
NameError: name 'models' is not defined
"GET /estadisticas/ HTTP/1.1" 500 68932
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /estadisticas/ HTTP/1.1" 200 12572
"GET / HTTP/1.1" 200 17540
"GET /autores/ HTTP/1.1" 200 11437
"GET /estadisticas/ HTTP/1.1" 200 12572
"GET / HTTP/1.1" 200 17540
"GET /autores/ HTTP/1.1" 200 11437
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET /autores/ HTTP/1.1" 200 11437
"GET / HTTP/1.1" 200 17540
"GET /autores/ HTTP/1.1" 200 11437
"GET / HTTP/1.1" 200 17540
"GET / HTTP/1.1" 200 17540
"GET /estadisticas/ HTTP/1.1" 200 12572
"GET /buscar/?q= HTTP/1.1" 200 11489
"GET / HTTP/1.1" 200 17540
"GET /estadisticas/ HTTP/1.1" 200 12572
"GET / HTTP/1.1" 200 17540
"GET /admin/ HTTP/1.1" 200 9041
"GET /admin/news/articulo/add/ HTTP/1.1" 200 25229
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/css/forms.css HTTP/1.1" 200 8525
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/news/articulo/add/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19829
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET / HTTP/1.1" 200 39151
"GET /autores/ HTTP/1.1" 200 14378
Internal Server Error: /categoria/politica/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/politica/ HTTP/1.1" 500 83379
Internal Server Error: /autor/2/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autor_detail.html
"GET /autor/2/ HTTP/1.1" 500 83199
"GET / HTTP/1.1" 200 39151
Internal Server Error: /categoria/politica/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/politica/ HTTP/1.1" 500 83371
"GET /admin/news/articulo/add/ HTTP/1.1" 200 25229
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /admin/news/articulo/ HTTP/1.1" 200 19571
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"POST /admin/news/articulo/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19688
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET / HTTP/1.1" 200 24112
"GET /autores/ HTTP/1.1" 200 14378
Internal Server Error: /autor/1/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autor_detail.html
"GET /autor/1/ HTTP/1.1" 500 83199
"POST /admin/news/articulo/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19720
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /autores/ HTTP/1.1" 200 14378
"GET / HTTP/1.1" 200 39151
"GET /admin/news/articulo/4/change/ HTTP/1.1" 200 26434
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
"POST /admin/news/articulo/4/change/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19827
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4699
"GET / HTTP/1.1" 200 39217
"GET /media/articulos/_honkai_star_rail___castorice.jpeg HTTP/1.1" 200 53520
Internal Server Error: /categoria/tecnologia/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/tecnologia/ HTTP/1.1" 500 83391
"GET / HTTP/1.1" 200 40460
"GET /media/articulos/_honkai_star_rail___castorice.jpeg HTTP/1.1" 304 0
Internal Server Error: /categoria/tecnologia/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/tecnologia/ HTTP/1.1" 500 83391
"GET /admin/news/articulo/4/change/ HTTP/1.1" 200 26846
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/articulos/_honkai_star_rail___castorice.jpeg HTTP/1.1" 200 53520
Not Found: /favicon.ico
"POST /admin/news/articulo/4/change/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19827
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 40439
"GET /media/articulos/a1X9Td_q.jpeg HTTP/1.1" 200 35673
"GET / HTTP/1.1" 200 41679
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/a1X9Td_q.jpeg HTTP/1.1" 200 35673
Not Found: /favicon.ico
Internal Server Error: /categoria/tecnologia/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/tecnologia/ HTTP/1.1" 500 83391
"GET /admin/news/articulo/4/change/ HTTP/1.1" 200 26783
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/articulos/a1X9Td_q.jpeg HTTP/1.1" 200 35673
"POST /admin/news/articulo/4/change/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19827
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4699
"GET / HTTP/1.1" 200 41687
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/a1X9Td_q_odnJsNU.jpeg HTTP/1.1" 200 35673
Not Found: /favicon.ico
"GET /admin/news/articulo/4/change/ HTTP/1.1" 200 26807
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/articulos/a1X9Td_q_odnJsNU.jpeg HTTP/1.1" 200 35673
"POST /admin/news/articulo/4/change/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 19827
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
"GET /autores/ HTTP/1.1" 200 15621
Internal Server Error: /autor/2/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autor_detail.html
"GET /autor/2/ HTTP/1.1" 500 83199
Internal Server Error: /categoria/deportes/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/deportes/ HTTP/1.1" 500 83379
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
Internal Server Error: /categoria/tecnologia/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/categoria_detail.html
"GET /categoria/tecnologia/ HTTP/1.1" 500 83391
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /categoria/politica/ HTTP/1.1" 200 15257
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
Not Found: /favicon.ico
Internal Server Error: /articulo/1/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/articulo_detail.html
"GET /articulo/1/ HTTP/1.1" 500 83284
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /articulo/1/ HTTP/1.1" 200 16407
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /categoria/politica/ HTTP/1.1" 200 15257
Not Found: /favicon.ico
"GET /categoria/deportes/ HTTP/1.1" 200 15249
"GET /autores/ HTTP/1.1" 200 15621
Internal Server Error: /autor/2/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autor_detail.html
"GET /autor/2/ HTTP/1.1" 500 83199
Internal Server Error: /autor/1/
Traceback (most recent call last):
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willian/django-news-site-complete (3)/venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/autor_detail.html
"GET /autor/1/ HTTP/1.1" 500 83199
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /autor/1/ HTTP/1.1" 200 16674
Not Found: /favicon.ico
"GET /articulo/3/ HTTP/1.1" 200 16297
"GET /articulo/1/ HTTP/1.1" 200 16407
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
"GET /autores/ HTTP/1.1" 200 15621
"GET /autores/ HTTP/1.1" 200 15621
"GET /autor/2/ HTTP/1.1" 200 16933
Not Found: /favicon.ico
"GET /categoria/deportes/ HTTP/1.1" 200 15249
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET /autores/ HTTP/1.1" 200 15621
"GET /buscar/?q=tecnologia HTTP/1.1" 200 14674
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /placeholder.svg HTTP/1.1" 404 4711
Not Found: /favicon.ico
"GET /buscar/?q=Nueva+Ley+de+Protecci%C3%B3n+Ambiental+entra+en+vigor+en+Ecuador+ HTTP/1.1" 200 14725
Not Found: /favicon.ico
"GET /buscar/?q=Nueva+Ley+de+Protecci%C3%B3n+Ambiental+entra+en+vigor+en+Ecuador+ HTTP/1.1" 200 14725
Not Found: /favicon.ico
"GET /autores/ HTTP/1.1" 200 15621
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /articulo/1/ HTTP/1.1" 200 16407
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /admin/news/comentario/add/ HTTP/1.1" 200 16784
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /buscar/?q=Nueva+Ley+de+Protecci%C3%B3n+Ambiental+entra+en+vigor+en+Ecuador HTTP/1.1" 200 15600
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /buscar/?q=mundial+de+futbol+genera HTTP/1.1" 200 14688
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /articulo/2/ HTTP/1.1" 200 16306
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
/home/willian/django-news-site-complete (3)/news/views.py changed, reloading.
Watching for file changes with StatReloader
/home/willian/django-news-site-complete (3)/news/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
"GET /autores/ HTTP/1.1" 200 15621
"GET /categoria/deportes/ HTTP/1.1" 200 15249
"GET /autores/ HTTP/1.1" 200 15621
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /autores/ HTTP/1.1" 200 15621
"GET /autor/2/ HTTP/1.1" 200 16933
"GET /articulo/2/ HTTP/1.1" 200 16306
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /articulo/2/ HTTP/1.1" 200 16306
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /admin/ HTTP/1.1" 302 0
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /autores/ HTTP/1.1" 200 15621
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4231
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 13126
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /autores/ HTTP/1.1" 200 15621
"GET /autor/1/ HTTP/1.1" 200 16674
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /articulo/4/ HTTP/1.1" 200 16333
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /autores/ HTTP/1.1" 200 15621
"GET /autor/2/ HTTP/1.1" 200 16933
"GET /admin/ HTTP/1.1" 200 13126
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /admin/news/comentario/add/ HTTP/1.1" 200 16784
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /admin/news/articulo/1/change/?_to_field=id HTTP/1.1" 200 26578
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /admin/news/comentario/add/ HTTP/1.1" 200 16784
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"POST /admin/news/comentario/add/ HTTP/1.1" 302 0
"GET /admin/news/comentario/ HTTP/1.1" 200 15511
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/news/comentario/?q= HTTP/1.1" 200 15397
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /admin/news/articulo/1/change/ HTTP/1.1" 200 26529
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /articulo/1/ HTTP/1.1" 200 16407
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /buscar/?q= HTTP/1.1" 200 14821
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
"GET /articulo/1/ HTTP/1.1" 200 16407
"GET /categoria/tecnologia/ HTTP/1.1" 200 16162
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
"GET /autores/ HTTP/1.1" 200 15621
"GET /autor/2/ HTTP/1.1" 200 16933
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4968
/home/willian/django_noticia/news/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /categoria/tecnologia/ HTTP/1.1" 200 19900
"GET /categoria/tecnologia/ HTTP/1.1" 200 19900
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET /autores/ HTTP/1.1" 200 14937
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 15621
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /articulo/3/ HTTP/1.1" 200 30560
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"POST /api/comentario/ HTTP/1.1" 200 330
"GET /articulo/3/ HTTP/1.1" 200 30560
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /articulo/2/ HTTP/1.1" 200 30570
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /articulo/2/ HTTP/1.1" 200 30570
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /autores/ HTTP/1.1" 200 14937
"GET /estadisticas/ HTTP/1.1" 200 15747
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /autores/ HTTP/1.1" 200 14937
"GET /admin/news/autor/add/ HTTP/1.1" 200 17057
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"POST /admin/news/autor/add/ HTTP/1.1" 302 0
"GET /admin/news/autor/ HTTP/1.1" 200 16439
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /media/autores/hero-bg.jpg HTTP/1.1" 200 14727
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 14937
"GET /autores/ HTTP/1.1" 200 16254
"GET /media/autores/hero-bg.jpg HTTP/1.1" 304 0
"GET /autor/3/ HTTP/1.1" 200 16852
"GET /media/autores/hero-bg.jpg HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 41675
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /admin/news/articulo/add/ HTTP/1.1" 200 25273
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
"POST /admin/news/articulo/add/ HTTP/1.1" 302 0
"GET /admin/news/articulo/ HTTP/1.1" 200 21048
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
Not Found: /favicon.ico
"GET / HTTP/1.1" 200 43280
"GET /media/articulos/_333.jpeg HTTP/1.1" 200 39452
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/autores/hero-bg.jpg HTTP/1.1" 200 14727
Not Found: /favicon.ico
"GET /autores/ HTTP/1.1" 200 16254
Not Found: /favicon.ico
"GET /autor/3/ HTTP/1.1" 200 19582
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 200 72786
"GET /categoria/tecnologia/ HTTP/1.1" 200 22567
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 304 0
"GET /articulo/5/ HTTP/1.1" 200 33127
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 304 0
Not Found: /favicon.ico
"POST /api/comentario/ HTTP/1.1" 200 141
"GET /articulo/5/ HTTP/1.1" 200 33127
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 304 0
"GET /media/autores/hero-bg.jpg HTTP/1.1" 304 0
"GET /articulo/5/ HTTP/1.1" 200 33127
Not Found: /placeholder.svg
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 304 0
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET / HTTP/1.1" 200 43280
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /autores/ HTTP/1.1" 200 16254
"GET /media/autores/hero-bg.jpg HTTP/1.1" 304 0
"GET /admin/news/autor/ HTTP/1.1" 200 16235
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/autores/hero-bg.jpg HTTP/1.1" 200 14727
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /admin/news/autor/2/change/ HTTP/1.1" 200 17586
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"POST /admin/news/autor/2/change/ HTTP/1.1" 302 0
"GET /admin/news/autor/ HTTP/1.1" 200 16522
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 200 37059
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /autores/ HTTP/1.1" 200 16389
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 304 0
"GET /admin/news/autor/1/change/ HTTP/1.1" 200 17590
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"POST /admin/news/autor/1/change/ HTTP/1.1" 302 0
"GET /admin/news/autor/ HTTP/1.1" 200 16605
"GET /admin/jsi18n/ HTTP/1.1" 200 8691
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 200 11214
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 200 37059
"GET /media/autores/hero-bg.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4699
"GET /autores/ HTTP/1.1" 200 16522
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 200 11214
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 200 37059
"GET / HTTP/1.1" 200 43042
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 304 0
Not Found: /placeholder.svg
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 304 0
"GET /placeholder.svg HTTP/1.1" 404 4711
Not Found: /favicon.ico
"GET /autores/ HTTP/1.1" 200 16522
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 304 0
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 304 0
"GET /autores/ HTTP/1.1" 200 15169
"GET /autores/ HTTP/1.1" 200 15169
"GET /autores/ HTTP/1.1" 200 16522
"GET /media/autores/hero-bg.jpg HTTP/1.1" 200 14727
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 304 0
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 304 0
Not Found: /favicon.ico
/home/willian/django_noticia/news/views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 43042
Not Found: /placeholder.svg
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 200 11214
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 200 37059
Not Found: /favicon.ico
"GET /media/articulos/_333.jpeg HTTP/1.1" 304 0
/home/willian/django_noticia/news/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 43042
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
"GET /media/autores/naTW0BFU.jpeg HTTP/1.1" 200 37059
"GET /media/autores/noQHGJmP.jpeg HTTP/1.1" 200 11214
"GET /media/autores/hero-bg.jpg HTTP/1.1" 200 14727
Not Found: /favicon.ico
"GET /autores/ HTTP/1.1" 200 24271
"GET /autor/3/ HTTP/1.1" 200 19583
"GET /media/articulos/A_intelig%C3%AAncia_artificial_IA_%C3%A9_um_ramo_da.jpeg HTTP/1.1" 304 0
"GET /categoria/tecnologia/ HTTP/1.1" 200 22568
"GET /articulo/5/ HTTP/1.1" 200 36296
Not Found: /placeholder.svg
"GET /placeholder.svg HTTP/1.1" 404 4711
